import "./globals.css";
import type { Metadata } from "next";
import {edu_QLD_Beginner, roboto } from "@/app/Font/font";
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${edu_QLD_Beginner.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
